repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: trailing-whitespace
        args: [
            "--markdown-linebreak-ext=md",
            ]

-   repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    -   id: black

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.249
    hooks:
    -   id: ruff
        args: [
            "--fix",
            "--force-exclude",
            ]

-   repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        args: [
            "-r",
            "-v",
            "-ll",
            ]
