repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: trailing-whitespace
        args: [
            "--markdown-linebreak-ext=md",
            ]

-   repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
    -   id: black

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.3
    hooks:
    -   id: ruff
        args: [
            "--fix",
            ]

-   repo: https://github.com/pycqa/bandit
    rev: 1.8.6
    hooks:
    -   id: bandit
        args: [
            "-r",
            "-v",
            "-ll",
            ]
