# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
# trigger:
#   batch: true
#   branches:
#     include:
#     - master
#   paths:
#     exclude:
#     - README.md
trigger:
  tags:
    include:
    - v*

# Opt out of pull request validation
pr: none

# By default, use self-hosted agents
pool: Default

resources:
  repositories:
  # Azure DevOps repository
  - repository: hitastj-pipelines
    type: git
    # Azure DevOps project/repository
    name: hitastj/hitastj-pipelines

extends:
  # Filename in Azure DevOps Repository (note possible -ui or -api)
  template: azure-pipelines-build-hitastj-api-test-staging.yml@hitastj-pipelines
