# Generated by Django 3.2.18 on 2023-05-22 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="housingcompany",
            name="state",
        ),
    ]
