# Generated by Django 3.2.18 on 2023-05-22 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0002_remove_housingcompany_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="housingcompany",
            name="financing_method",
        ),
        migrations.DeleteModel(
            name="FinancingMethod",
        ),
    ]
