# Generated by Django 3.2.18 on 2023-05-30 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0003_remove_financing_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="state",
        ),
    ]
