# Generated by Django 3.2.18 on 2023-06-12 10:17

import enumfields.fields
from django.db import migrations, models

import hitas.models._base
import hitas.models.email_template


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0004_remove_apartment_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    enumfields.fields.EnumField(
                        enum=hitas.models.email_template.EmailTemplateName,
                        max_length=33,
                        unique=True,
                    ),
                ),
                ("text", models.TextField(max_length=10000)),
            ],
            options={
                "verbose_name": "Email template",
                "verbose_name_plural": "Email templates",
            },
            bases=(
                hitas.models._base.PostFetchModelMixin,
                hitas.models._base.AuditLogAdditionalDataMixin,
                models.Model,
            ),
        ),
    ]
