# Generated by Django 3.2.15 on 2022-08-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hitas", "0006_floor_to_string"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="completion_date",
        ),
        migrations.AddField(
            model_name="apartment",
            name="completion_date",
            field=models.DateField(null=True),
        ),
    ]
