# Generated by Django 3.2.18 on 2023-06-12 12:44

import django.contrib.postgres.fields
import enumfields.fields
from django.db import migrations, models

import hitas.models._base
import hitas.models.pdf_body


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0006_alter_email_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    enumfields.fields.EnumField(
                        enum=hitas.models.pdf_body.PDFBodyName,
                        max_length=33,
                        unique=True,
                    ),
                ),
                (
                    "texts",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(max_length=10000),
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF body",
                "verbose_name_plural": "PDF bodies",
            },
            bases=(
                hitas.models._base.PostFetchModelMixin,
                hitas.models._base.AuditLogAdditionalDataMixin,
                models.Model,
            ),
        ),
    ]
