# Generated by Django 3.2.19 on 2023-06-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0007_pdfbody"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertymanager",
            name="city",
        ),
        migrations.RemoveField(
            model_name="propertymanager",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="propertymanager",
            name="street_address",
        ),
        migrations.AlterField(
            model_name="propertymanager",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
