# Generated by Django 3.2.15 on 2022-08-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitas', '0007_completion_date_to_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='building',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='postal_code',
        ),
    ]
