# Generated by Django 3.2.15 on 2022-08-29 07:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hitas.models._base
import hitas.models.utils


def migrate_owners(apps, schema_editor):
    Owner = apps.get_model('hitas', 'Owner')
    Ownership = apps.get_model('hitas', 'Ownership')

    for old in Owner.objects.all():
        new = Ownership()
        new.id = old.id
        new.apartment_id = old.apartment_id
        new.owner_id = old.person_id
        new.percentage = old.ownership_percentage
        new.start_date = old.ownership_start_date
        new.end_date = old.ownership_end_date

        new.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hitas', '0008_remove_postal_code_from_real_estate_building_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', hitas.models._base.HitasModelDecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownerships', to='hitas.apartment')),
            ],
            options={
                'verbose_name': 'Ownership',
                'verbose_name_plural': 'Ownerships',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='person',
            name='street_address',
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownerships', to='hitas.person'),
        ),
        migrations.RunPython(migrate_owners),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
