# Generated by Django 3.2.19 on 2023-08-21 12:06
import datetime

from django.db import migrations
from django.db.models import Case, F, Q, When

from hitas.models._base import HitasModelDecimalField
from hitas.models.housing_company import HitasType


def migrate_apartment_interests(apps, schema_editor):
    # Prepare values for migration from interest_during_construction_6 and interest_during_construction_14
    # to interest_during_construction_cpi and interest_during_construction_mpi

    Apartment = apps.get_model("hitas", "apartment")

    Apartment.objects.exclude(
        building__real_estate__housing_company__hitas_type__in=HitasType.with_new_hitas_ruleset()
    ).filter(
        interest_during_construction_6__gt=0,
        interest_during_construction_14__gt=0,
    ).annotate(
        _construction_price_index_interest=Case(
            When(
                condition=Q(completion_date__lt=datetime.date(2005, 1, 1)),
                then=F("interest_during_construction_14"),
            ),
            default=F("interest_during_construction_6"),
            output_field=HitasModelDecimalField(),
        ),
    ).update(
        interest_during_construction_14=F("_construction_price_index_interest")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0009_job_performance_multi_relation"),
    ]

    operations = [
        migrations.RunPython(migrate_apartment_interests, migrations.RunPython.noop),
    ]
