# Generated by Django 3.2.15 on 2022-08-30 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitas', '0009_rename_owner_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='share_number_end',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='share_number_start',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
