# Generated by Django 4.2.4 on 2023-09-19 10:58

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0011_rename_interest_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="NonObfuscatedOwner",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("hitas.owner",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
