# Generated by Django 3.2.15 on 2022-08-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hitas", "0012_apartment_database_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
