# Generated by Django 4.2.4 on 2024-06-19 09:32

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

import hitas.models._base
import hitas.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0014_apartment_updated_acquisition_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="HousingCompanyDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("display_name", models.CharField(max_length=1024)),
                ("original_filename", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=hitas.models.document.DocumentFilenameGenerator("housingcompany_documents")
                    ),
                ),
                (
                    "housing_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="hitas.housingcompany"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                hitas.models._base.PostFetchModelMixin,
                hitas.models._base.AuditLogAdditionalDataMixin,
                models.Model,
            ),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AparmentDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("display_name", models.CharField(max_length=1024)),
                ("original_filename", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(upload_to=hitas.models.document.DocumentFilenameGenerator("apartment_documents")),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="hitas.apartment"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                hitas.models._base.PostFetchModelMixin,
                hitas.models._base.AuditLogAdditionalDataMixin,
                models.Model,
            ),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
