# Generated by Django 3.2.15 on 2022-09-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitas', '0016_apartment_hitas_apartment_share_number_both_set'),
    ]

    operations = [
        migrations.RunSQL("""
            UPDATE hitas_housingcompany
                SET display_name=display_name || '-migration-' || id
                WHERE id in (
                    SELECT id FROM hitas_housingcompany WHERE display_name in (
                        SELECT display_name FROM hitas_housingcompany GROUP BY display_name HAVING COUNT(*) > 1
                    )
                );
        """),
        migrations.AlterField(
            model_name='housingcompany',
            name='display_name',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='housingcompany',
            name='official_name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
