# Generated by Django 4.2.16 on 2025-01-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hitas", "0016_external_report_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aparmentdocument",
            name="modified_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="housingcompanydocument",
            name="modified_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
