# Generated by Django 3.2.15 on 2022-09-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0017_fix_unique_housing_company_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housingcompany",
            name="display_name",
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name="housingcompany",
            name="official_name",
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
