# Generated by Django 5.2.4 on 2025-07-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hitas", "0017_alter_aparmentdocument_modified_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownership",
            name="conditions_of_sale",
            field=models.ManyToManyField(
                through="hitas.ConditionOfSale", through_fields=("new_ownership", "old_ownership"), to="hitas.ownership"
            ),
        ),
    ]
