# Generated by Django 5.2.7 on 2025-10-10 07:51

import uuid
from decimal import Decimal
from django.db import migrations, models
import django.core.validators
import hitas.models._base


def set_ownership_uuids(apps, schema_editor):
    Ownership = apps.get_model("hitas", "Ownership")
    for ownership in Ownership.objects.all():
        ownership.uuid = uuid.uuid4()
        ownership.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("hitas", "0018_noop_migration_from_upgrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='percentage',
            field=hitas.models._base.HitasModelDecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name="ownership",
            name="uuid",
            field=models.UUIDField(null=True, editable=False, unique=True),
        ),
        migrations.RunPython(set_ownership_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="ownership",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
