# Generated by Django 3.2.15 on 2022-09-13 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0018_unique_housing_company_names"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financingmethod",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Financing method",
                "verbose_name_plural": "Financing methods",
            },
        ),
    ]
