# Generated by Django 3.2.15 on 2022-09-21 12:48

import django.db.models.deletion
import enumfields.fields
from django.db import migrations, models

import hitas.models.apartment


class Migration(migrations.Migration):

    dependencies = [
        ("hitas", "0019_alter_financingmethod_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="HousingCompanyMarketPriceImprovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=128)),
                ("completion_date", models.DateField()),
                ("value", models.PositiveIntegerField(default=0)),
                (
                    "housing_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_price_improvements",
                        to="hitas.housingcompany",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HousingCompanyConstructionPriceImprovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=128)),
                ("completion_date", models.DateField()),
                ("value", models.PositiveIntegerField(default=0)),
                (
                    "housing_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="construction_price_improvements",
                        to="hitas.housingcompany",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApartmentMarketPriceImprovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=128)),
                ("completion_date", models.DateField()),
                ("value", models.PositiveIntegerField(default=0)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_price_improvements",
                        to="hitas.apartment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApartmentConstructionPriceImprovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=128)),
                ("completion_date", models.DateField()),
                ("value", models.PositiveIntegerField(default=0)),
                (
                    "depreciation_percentage",
                    enumfields.fields.EnumField(
                        default=10.0, enum=hitas.models.apartment.DepreciationPercentage, max_length=10
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="construction_price_improvements",
                        to="hitas.apartment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
