# Generated by Django 5.2.7 on 2025-10-13 11:50

import re

import django.core.validators
import django.db.models.functions.comparison
from django.db import migrations, models


def copy_apartment_numbers(apps, schema_editor):
    Apartment = apps.get_model('hitas', 'Apartment')
    for apartment in Apartment.objects.all():
        apartment.apartment_number = apartment.apartment_number_integer or ''
        apartment.save(update_fields=['apartment_number'])


def copy_apartment_numbers_reverse(apps, schema_editor):
    Apartment = apps.get_model('hitas', 'Apartment')
    for apartment in Apartment.objects.all():
        try:
            apartment.apartment_number_integer = int(apartment.apartment_number)
        except ValueError:
            apartment.apartment_number_integer = None
        apartment.save(update_fields=['apartment_number_integer'])


class Migration(migrations.Migration):

    dependencies = [
        ('hitas', '0019_ownership_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='apartment_number',
            new_name='apartment_number_integer',
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Sallittuja ovat vain numerot, ja numeroiden perässä kirjaimet.', regex='^\\d+[a-z]*$')]),
            preserve_default=False,
        ),
        migrations.RunPython(copy_apartment_numbers, reverse_code=copy_apartment_numbers_reverse),
        # GeneratedField cannot be altered, so we need to drop and recreate it
        migrations.RemoveField(
            model_name='apartment',
            name='apartment_number_integer',
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_number_integer',
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Cast(
                    django.db.models.functions.comparison.NullIf(
                        models.Func(
                            models.F('apartment_number'),
                            models.Value('\\D+'),
                            models.Value(''),
                            models.Value('g'),
                            function='REGEXP_REPLACE'
                        ),
                        models.Value('')
                    ),
                    output_field=models.IntegerField()
                ),
                output_field=models.IntegerField()
            ),
        ),
    ]
