# Generated by Django 3.2.15 on 2022-09-28 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0020_improvements"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apartmentconstructionpriceimprovement",
            options={"ordering": ["completion_date", "id"]},
        ),
        migrations.AlterModelOptions(
            name="apartmentmarketpriceimprovement",
            options={"ordering": ["completion_date", "id"]},
        ),
        migrations.AlterModelOptions(
            name="housingcompanyconstructionpriceimprovement",
            options={"ordering": ["completion_date", "id"]},
        ),
        migrations.AlterModelOptions(
            name="housingcompanymarketpriceimprovement",
            options={"ordering": ["completion_date", "id"]},
        ),
    ]
