# Generated by Django 3.2.15 on 2022-09-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitas', '0021_improvement_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingcompany',
            name='legacy_id',
        ),
    ]
