# Generated by Django 3.2.15 on 2022-10-12 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitas', '0029_rename_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='rooms',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
