# Generated by Django 3.2.16 on 2022-11-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitas', '0032_apartmentmaxpricecalculation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApartmentMaxPriceCalculation',
            new_name='ApartmentMaximumPriceCalculation',
        ),
        migrations.RenameModel(
            old_name='MaxPriceIndex',
            new_name='MaximumPriceIndex',
        ),
        migrations.AlterModelOptions(
            name='maximumpriceindex',
            options={'verbose_name': 'Maximum price index', 'verbose_name_plural': 'Maximum price indices'},
        ),
        migrations.RenameField(
            model_name='apartmentmaximumpricecalculation',
            old_name='max_price',
            new_name='maximum_price',
        ),
    ]
