# Generated by Django 3.2.16 on 2022-11-04 07:38

import django.core.validators
import rest_framework.utils.encoders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hitas", "0034_migrationdone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentmaximumpricecalculation",
            name="json",
            field=models.JSONField(encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="apartmentmaximumpricecalculation",
            name="json_version",
            field=models.SmallIntegerField(
                default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
