# Generated by Django 3.2.16 on 2022-11-07 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0035_apartment_max_price_calc_json_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentmaximumpricecalculation",
            name="json_version",
            field=models.SmallIntegerField(
                default=2, null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
