# Generated by Django 3.2.16 on 2022-12-08 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitas', '0040_apartment_json_encoder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apartments', to='hitas.apartmenttype'),
        ),
    ]
