# Generated by Django 3.2.16 on 2022-12-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0042_financing_method_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="valid_ssn",
            field=models.BooleanField(default=False),
        ),
    ]
