# Generated by Django 3.2.16 on 2022-12-14 12:54

from django.db import migrations, models
import hitas.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hitas', '0043_owner_valid_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingcompany',
            name='business_id',
            field=models.CharField(help_text='Format: 1234567-1', max_length=9, null=True, validators=[hitas.models.utils.validate_business_id]),
        ),
    ]
