# Generated by Django 3.2.16 on 2022-12-14 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0044_alter_housingcompany_business_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="owner",
            old_name="valid_ssn",
            new_name="valid_identifier",
        ),
    ]
