# Generated by Django 3.2.16 on 2022-12-16 10:43

from decimal import Decimal
import django.core.validators
from django.db import migrations
import hitas.models._base


class Migration(migrations.Migration):

    dependencies = [
        ('hitas', '0045_rename_valid_ssn_owner_valid_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='interest_during_construction',
        ),
        migrations.AddField(
            model_name='apartment',
            name='interest_during_construction_14',
            field=hitas.models._base.HitasModelDecimalField(decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='apartment',
            name='interest_during_construction_6',
            field=hitas.models._base.HitasModelDecimalField(decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
