# Generated by Django 3.2.16 on 2023-01-09 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hitas", "0047_change_on_delete_rules_to_protect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentmaximumpricecalculation",
            name="json_version",
            field=models.SmallIntegerField(
                default=5, null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
