# Generated by Django 3.2.16 on 2023-01-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0049_add_sale_and_make_ownership_static"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartmentsale",
            name="include_in_statistics",
        ),
        migrations.AddField(
            model_name="apartmentsale",
            name="exclude_in_statistics",
            field=models.BooleanField(default=False),
        ),
    ]
