# Generated by Django 3.2.16 on 2023-01-13 13:43

import uuid

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Ownership = apps.get_model("hitas", "Ownership")
    for row in Ownership.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("hitas", "0050_change_apartment_sale_statistics_field_name"),
    ]

    operations = [
        # From django docs:
        # https://docs.djangoproject.com/en/3.2/howto/writing-migrations/#migrations-that-add-unique-fields
        #
        # Note there is a race condition if we allow objects to be created while this migration is running.
        # Objects created after the AddField and before RunPython will have their original uuid’s overwritten.
        migrations.AddField(
            model_name="ownership",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="ownership",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
