# Generated by Django 3.2.16 on 2023-01-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hitas", "0051_add_condition_of_sale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apartmentsale",
            options={
                "ordering": ["-purchase_date"],
                "verbose_name": "Apartment sale",
                "verbose_name_plural": "Apartment sales",
            },
        ),
    ]
