# Generated by Django 3.2.16 on 2023-01-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hitas", "0052_alter_apartmentsale_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ownership",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="ownership",
            name="start_date",
        ),
    ]
