# Generated by Django 3.2.16 on 2023-02-09 11:28

from django.db import migrations, models

import hitas.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ("hitas", "0055_alter_owner_bypass_conditions_of_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestate",
            name="property_identifier",
            field=models.CharField(
                help_text="Format: 1234-1234-1234-1234",
                max_length=19,
                null=True,
                validators=[hitas.models.utils.validate_property_id],
            ),
        ),
    ]
