# Generated by Django 3.2.16 on 2023-02-09 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hitas", "0055_alter_owner_bypass_conditions_of_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="debt_free_purchase_price",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="first_purchase_date",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="latest_purchase_date",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="primary_loan_amount",
        ),
    ]
