# Generated by Django 3.2.16 on 2023-02-10 15:33


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hitas", "0056_remove_apartment_first_sale_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="purchase_price",
        ),
    ]
