# Generated by Django 3.2.16 on 2023-02-10 15:33

from decimal import Decimal

import django.core.validators
from django.db import migrations

import hitas.models._base


class Migration(migrations.Migration):

    dependencies = [
        ("hitas", "0057_remove_apartment_purchase_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="catalog_primary_loan_amount",
            field=hitas.models._base.HitasModelDecimalField(
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="catalog_purchase_price",
            field=hitas.models._base.HitasModelDecimalField(
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
