# Generated by Django 3.2.16 on 2023-02-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0059_remove_apartment_purchase_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalSalesData",
            fields=[
                ("calculation_quarter", models.CharField(max_length=6, primary_key=True, serialize=False)),
                ("quarter_1", models.JSONField()),
                ("quarter_2", models.JSONField()),
                ("quarter_3", models.JSONField()),
                ("quarter_4", models.JSONField()),
            ],
            options={
                "verbose_name": "External sales data",
                "verbose_name_plural": "External sales datas",
            },
        ),
    ]
