# Generated by Django 3.2.18 on 2023-02-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0060_externalsalesdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentmarketpriceimprovement",
            name="no_deductions",
            field=models.BooleanField(default=False),
        ),
    ]
