# Generated by Django 3.2.18 on 2023-03-09 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0061_add_no_deductions_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apartmentsale",
            old_name="exclude_in_statistics",
            new_name="exclude_from_statistics",
        ),
    ]
