# Generated by Django 3.2.18 on 2023-03-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0063_add_no_deductions_field_hc"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurfaceAreaPriceCeilingCalculationData",
            fields=[
                ("calculation_month", models.DateField(primary_key=True, serialize=False)),
                ("data", models.JSONField()),
            ],
            options={
                "verbose_name": "Surface area price ceiling calculation data",
                "verbose_name_plural": "Surface area price ceiling calculation data",
            },
        ),
    ]
