# Generated by Django 3.2.18 on 2023-03-20 12:04

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import enumfields.fields
from django.db import migrations, models

import hitas.models._base
import hitas.models.thirty_year_regulation


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0064_surfaceareapriceceilingcalculationdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThirtyYearRegulationResults",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("calculation_month", models.DateField()),
                ("regulation_month", models.DateField()),
                (
                    "surface_area_price_ceiling",
                    hitas.models._base.HitasModelDecimalField(
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("sales_data", models.JSONField()),
            ],
            options={
                "verbose_name": "Thirty Year Regulation Results",
                "verbose_name_plural": "Thirty Year Regulation Results",
            },
        ),
        migrations.CreateModel(
            name="ThirtyYearRegulationResultsRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completion_date", models.DateField()),
                (
                    "surface_area",
                    hitas.models._base.HitasModelDecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("postal_code", models.CharField(max_length=5)),
                (
                    "realized_acquisition_price",
                    hitas.models._base.HitasModelDecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "unadjusted_average_price_per_square_meter",
                    hitas.models._base.HitasModelDecimalField(
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "adjusted_average_price_per_square_meter",
                    hitas.models._base.HitasModelDecimalField(
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "completion_month_index",
                    hitas.models._base.HitasModelDecimalField(
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "calculation_month_index",
                    hitas.models._base.HitasModelDecimalField(
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "regulation_result",
                    enumfields.fields.EnumField(
                        enum=hitas.models.thirty_year_regulation.RegulationResult, max_length=24
                    ),
                ),
                (
                    "housing_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="hitas.housingcompany"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="hitas.thirtyyearregulationresults",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thirty Year Regulation Results Row",
                "verbose_name_plural": "Thirty Year Regulation Results Rows",
            },
        ),
    ]
