# Generated by Django 3.2.18 on 2023-03-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0065_thirtyyearregulationresults_thirtyyearregulationresultsrow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thirtyyearregulationresults",
            name="calculation_month",
            field=models.DateField(unique=True),
        ),
    ]
