# Generated by Django 3.2.18 on 2023-03-28 12:49

import enumfields.fields
from django.db import migrations

import hitas.models.housing_company


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0066_alter_thirtyyearregulationresults_calculation_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="housingcompany",
            name="hitas_type",
            field=enumfields.fields.EnumField(
                default=hitas.models.housing_company.HitasType.HITAS_I,
                enum=hitas.models.housing_company.HitasType,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
