# Generated by Django 3.2.18 on 2023-03-30 07:37

import enumfields.fields
from django.db import migrations, models

import hitas.models.housing_company


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0067_housingcompany_hitas_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="housingcompany",
            name="exclude_from_statistics",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="housingcompany",
            name="regulation_status",
            field=enumfields.fields.EnumField(
                default="regulated",
                enum=hitas.models.housing_company.RegulationStatus,
                max_length=27,
            ),
        ),
    ]
