# Generated by Django 3.2.18 on 2023-04-03 08:58
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0068_add_statistics_and_regulation_fields_to_housing_company"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ownership",
            name="hitas_ownership_single_ownership_for_apartment_per_owner",
        ),
        migrations.RemoveField(
            model_name="ownership",
            name="apartment",
        ),
    ]
