# Generated by Django 3.2.18 on 2023-04-03 08:58
from django.db import migrations


def remove_ownerships_without_sales(apps, schema_editor):
    Ownership = apps.get_model("hitas", "Ownership")
    Ownership.objects.filter(sale=None).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0069_remove_ownership_apartment"),
    ]

    operations = [
        # This is a temporary measure to enable smoother migration.
        # We'll rerun migrations at some point so that all ownerships will have sales.
        migrations.RunPython(remove_ownerships_without_sales),
    ]
