# Generated by Django 3.2.18 on 2023-04-03 08:58
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0070_remove_ownerships_with_null_sales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownership",
            name="sale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownerships",
                to="hitas.apartmentsale",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted__isnull", True)),
                fields=("sale", "owner"),
                name="hitas_ownership_single_ownership_for_sale_per_owner",
            ),
        ),
    ]
