# Generated by Django 3.2.18 on 2023-04-27 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0071_make_ownership_sale_not_nullable"),
    ]

    operations = [
        migrations.RenameField(
            model_name="housingcompany",
            old_name="notification_date",
            new_name="legacy_release_date",
        ),
    ]
