# Generated by Django 3.2.18 on 2023-05-05 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0074_thirtyyearregulationresultsrow_letter_fetched"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realestate",
            name="street_address",
        ),
    ]
