# Generated by Django 3.2.18 on 2023-05-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0074_thirtyyearregulationresultsrow_letter_fetched"),
    ]

    operations = [
        migrations.AddField(
            model_name="thirtyyearregulationresults",
            name="replacement_postal_codes",
            field=models.JSONField(default=list),
            preserve_default=False,
        ),
    ]
