# Generated by Django 3.2.18 on 2023-05-05 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0075_thirtyyearregulationresults_replacement_postal_codes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realestate",
            name="street_address",
        ),
    ]
