# Generated by Django 3.2.18 on 2023-05-12 08:02

import django.db.models.deletion
import enumfields.fields
from django.conf import settings
from django.db import migrations, models

import hitas.models._base
import hitas.models.job_performance


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hitas", "0076_remove_realestate_street_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPerformance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    enumfields.fields.EnumField(enum=hitas.models.job_performance.JobPerformanceSource, max_length=21),
                ),
                ("request_date", models.DateField(editable=False)),
                ("delivery_date", models.DateField(editable=False)),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_performances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job performance",
                "verbose_name_plural": "Job performances",
            },
            bases=(hitas.models._base.PostFetchModelMixin, models.Model),
        ),
    ]
