# Generated by Django 3.2.18 on 2023-05-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hitas", "0077_jobperformance"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="non_disclosure",
            field=models.BooleanField(default=False),
        ),
    ]
