# Generated by Django 5.2.4 on 2025-09-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_phone_and_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_api_use',
            field=models.DateField(blank=True, null=True, verbose_name='Latest API token usage date'),
        ),
    ]
